appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a83aeb3c070044c6ac
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: VmooTpzoLnuPwJX0/Z5/S76dYc/GYd4eCusz0uIpO6q27Mm1bq/S6UuQMdEANsdEVJsCh9nTxhOBc4HiLHomzYTYcxU10idIomTgDE27RtST49I/+wZW3Vk2fKmkSXd0vOLyUsznnSF/lxht5lTIpW7Gn9goERGeOy+RocTfk2hC9K+81dwAYAKZ/ht1YXbiK5oqjTN8uKJyWsQXbIfTFVbunq7Gg4uH6dfYnUhagDwZjG1Czld1sOCkGAEdztWq5JP7GnYyG1dR3aj2DX3rOSJC7WKzBRuVHCdNqYW7vClrKC/PqnQzyZMJcLp8517euLN7xbLaMU4Cqqqb5AFLdexWAopkNUy4Nnmjr0/VkhYTF81+S3ZYa6Astf0bwLD8RUqehc/zXDId569G21sSy2eoHAWFYceOLT4lLjPanLcMr9Ix+hmbncoQw9t1mlylQB6gpVhV62hi3z+ciJn6kJeCiUpwTPSUDMnjouTL4xz3tnqU9LgDwvXd7gdM+l7gatP9w7lcC0v3AgRoE1iUvNj4IyuT5wXQ4oWfehscXP6l68KzNfn+YmM0phFy+8Yx8zNjN67F9xoEBMN0Qmx57q/gnkZ2PYXe4mbVauqWnzRyVwgtL83hioxQ3lUS/mvuMZooLTASxLROGCkm2w1vbA7AYZSE4i1Baxl4jIZeVDE=}
